Azure/c-build-tools

traceabilitytool/traceability_tool/packages.config
traceabilitytool/traceability_tool/traceabilitytool.csproj

Add Nuget dependency for DocumentFormat.OpenXml

Add Nuget dependency for DocumentFormat.OpenXml

---

.gitignore
CMakeLists.txt

Add missing CMakeLists.Txt

---

test_build_functions/CMakeLists.txt

Minor update for new C util:
- A function was previously missed from C build tools
- Attempt always to link the logging files

Minor update for new C util

---

CMakeLists.txt
build/devops.yml
build/linux/build_linux.sh
test_build_functions/CMakeLists.txt

Add Linux build

---

traceabilitytool/traceability_tool/traceabilitytool.csproj

remove signing properties from traceability csproj

remove signing properties

---

test_build_functions/CMakeLists.txt
test_build_functions/nothing.cpp

Fix linking logging lib

---

CMakeLists.txt
test_build_functions/CMakeLists.txt

Add warnings as errors to be default in C build tools

Add warnings as errors to be default in C build tools

---

test_build_functions/CMakeLists.txt

Apply wd4200 for C++ also

---

build_functions/CMakeLists.txt

New cmake functions didn't add valgrind tests for Linux

Add valgrind and friends back for linux

---

build_functions/CMakeLists.txt

Enable link time code generation

Enable link time code generation

---

build_functions/CMakeLists.txt

Add USE_VALGRIND define

---

build_functions/CMakeLists.txt

Add debugging info for Linux builds

Add debugging info for Linux builds

---

CMakeLists.txt

Fix valgrind options

---

build_functions/CMakeLists.txt
build_functions/disable_vld.ini

Disable VLD for Dlls

---

CMakeLists.txt

Do not build traceability tool when run_traceability is OFF

Do not build traceability tool when run_traceability is OFF

---

CMakeLists.txt
build/devops.yml
build_functions/CMakeLists.txt
iwyu/rules.imp

- Add basic rules for iwyu
- Guard manifest embedding by generator being Visual Studio

Add basic rules for iwyu

---

iwyu/rules.imp

iwyu rules resulting from enabling it on ctestrunnerswitcher

iwyu rules resulting from enabling it on ctestrunnerswitcher

---

build_functions/CMakeLists.txt

Fix cppunittest include and lib references

Fix cppunittest include and lib references

---

iwyu/rules.imp

Rules for iwyu found during c-pal includecheck

Rules for iwyu found during c-pal includecheck

---

iwyu/rules.imp

Fixing more Linux iwyu

---

build/devops.yml

Use Linux build machine pool

---

update_deps/build_graph.ps1

Changed script to use loop instead of recursion to avoid call depth overflow issue.

Fix script

---

update_deps/propagate_updates.ps1

Remove deps folder to refresh deps.
For some reason, sometimes submodule updates don't get detected. Deleting the deps folder fixes that problem somehow.

refresh deps

---

build/devops.yml
srs_extension/package-lock.json
srs_extension/package.json
srs_extension/test/memfs.js
srs_extension/test/runTest.js
srs_extension/test/suite/editor.int.test.js
srs_extension/test/suite/index.js

Attempting to fix srs extension node tests with the vs2022 changes

Vs2022 srs fix

---

.github/fabricbot.json

Add fabricbot settings

---

.github/fabricbot.json

Add Bingyi to the fabric bot config

Add Bingyi to the fabric bot config

---

build_functions/CMakeLists.txt

Add another function to install headers only by default.

Add another function to install headers only by default.

---

pipeline_templates/README.md
pipeline_templates/disable_appverifier.yml
pipeline_templates/run_ctests_with_appverifier.yml
pipeline_templates/scripts/appverifier_ctest_tests_helper.ps1
pipeline_templates/scripts/enable_appverifier_ctest_tests.ps1

Adds pipeline templates for running tests with application verifier

Helper yml for app verifier tests

---

pipeline_templates/README.md
pipeline_templates/codeql3000_finalize.yml
pipeline_templates/codeql3000_init.yml

Add 2 wrappers for Codeql3000 so that we do not triplicate the .ymls in all 3 main repos we have

Add 2 wrappers for Codeql3000 so that we do not triplicate the .ymls in all 3 main repos we have

---

pipeline_templates/codeql3000_default.yml

Add build type to CodeQL3000 default

Add build type to CodeQL3000 default

---

pipeline_templates/build_all_flavors.yml
pipeline_templates/build_and_run_tests.yml

-Add option to run without ctest so we can capture dumps
-Add start and stop of logman to capture etl logs

Add run without ctest and etl logging

---

pipeline_templates/build_all_flavors.yml
pipeline_templates/build_and_run_tests.yml

Optionally allow app verifier run in build_all_flavors

Appverif in pipeline template

---

build/devops.yml
pipeline_templates/build_and_run_tests.yml
pipeline_templates/codeql3000_default.yml
pipeline_templates/tttracer_stop.yml

use new hosted pool

---

pipeline_templates/get_machine_information.yml

Remove attempt to get Azure VM size - fails all the time

Remove attempt to get Azure VM size - fails all the time

---

pipeline_templates/run_master_check.yml

* added a powershell script that checks submodule's master sha
* be more leninent
* organize the check as template of JOBS
*cehckout submodules...

incremental check of submodules (#211)

---

pipeline_templates/clean_ado_folders.yml

Add script to clean ADO folders

Add script to clean ADO folders

---

pipeline_templates/build_and_run_tests.yml
pipeline_templates/codeql3000_default.yml

Use clean_ado_folders to cleanup leftovers

Use clean_ado_folders to cleanup leftovers

---

pipeline_templates/run_master_check.yml
pipeline_templates/scripts/submodule_master_check.ps1

Add ignore submodules parameter for master check in order to allow skipping specific submodules when performing the master check

Add ignore submodules parameter for master check
